AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false
