name: Makefile CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run linters
      run: make linter_run
